#!/bin/bash

if [ ${UID} -ne 0 ]
then
echo "You need root access"
exit 1
fi

## Check number of processors

 if [ `nproc` -eq 1 ]
 then
	 echo " this server is very small"
	 exit 3
 fi
 #checking memory
 free -m
 exit 0
